# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{img_gravatar}
  s.version = "1.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Till Salzer", "Jon Wood"]
  s.date = %q{2009-11-26}
  s.description = %q{Add a img_gravatar helper to ActiveView.}
  s.email = %q{till.salzer@googlemail.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "MIT-LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION.yml",
     "img_gravatar.gemspec",
     "init.rb",
     "install.rb",
     "lib/img_gravatar.rb",
     "spec/img_gravatar_spec.rb",
     "spec/module_gravatar_spec.rb",
     "spec/spec_helper.rb",
     "tasks/img_gravatar_tasks.rake",
     "uninstall.rb"
  ]
  s.homepage = %q{http://github.com/tsalzer/minimapper}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Gravatar image helper}
  s.test_files = [
    "spec/img_gravatar_spec.rb",
     "spec/module_gravatar_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

